FROM python:3.11-slim

WORKDIR /app

# Копируем зависимости
COPY requirements.txt .
# Если в requirements.txt нет gunicorn/psycopg2, добавим их
RUN pip install --no-cache-dir -r requirements.txt gunicorn psycopg2-binary flask-sqlalchemy

# Копируем код
COPY server_api.py .

# Запуск через Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "server_api:app"]
