-- Таблица лидеров (основной профиль игрока)
CREATE TABLE IF NOT EXISTS leaderboard (
    telegram_id BIGINT PRIMARY KEY,
    username TEXT NOT NULL,
    avatar_url TEXT,
    score BIGINT DEFAULT 0,
    high_score BIGINT DEFAULT 0,
    coins INTEGER DEFAULT 0,
    
    -- Бонусы (дефолт 2 по дампу)
    bonus_time INTEGER DEFAULT 2,
    bonus_hint INTEGER DEFAULT 2,
    bonus_swap INTEGER DEFAULT 2,
    bonus_wildcard INTEGER DEFAULT 2,
    
    -- Статистика
    streak INTEGER DEFAULT 0,
    total_words INTEGER DEFAULT 0,
    days_played INTEGER DEFAULT 0,
    rare_words JSONB DEFAULT '[]'::jsonb,
    
    daily_1_place INTEGER DEFAULT 0,
    daily_2_place INTEGER DEFAULT 0,
    daily_3_place INTEGER DEFAULT 0,
    
    marathon_high_score INTEGER DEFAULT 0,
    
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Ежедневные очки
CREATE TABLE IF NOT EXISTS daily_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL, -- Внимание: у вас нет внешнего ключа в дампе, но лучше его оставить для целостности, или убрать если Supabase его не форсил. Оставим без FK если в дампе его нет явно, но лучше добавить.
    challenge_id BIGINT,
    score INTEGER NOT NULL,
    game_date TEXT NOT NULL,
    
    username TEXT,
    avatar_url TEXT,
    
    bonus_time INTEGER DEFAULT 2,
    bonus_hint INTEGER DEFAULT 2,
    bonus_swap INTEGER DEFAULT 2,
    bonus_wildcard INTEGER DEFAULT 2,
    
    level_scores JSONB,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Челленджи
CREATE TABLE IF NOT EXISTS challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letters JSONB NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Отзывы
CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT,
    username TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'new',
    admin_reply TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Уведомления
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL,
    type TEXT NOT NULL,
    data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Рассылки
CREATE TABLE IF NOT EXISTS broadcasts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    sent_count BIGINT DEFAULT 0,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Индексы для скорости (их могло не быть в дампе колонок, но они нужны)
CREATE INDEX IF NOT EXISTS idx_leaderboard_score ON leaderboard (score DESC);
CREATE INDEX IF NOT EXISTS idx_daily_scores_challenge ON daily_scores (challenge_id, score DESC);
