-- Создаем таблицу для определений
CREATE TABLE IF NOT EXISTS definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NOT NULL,
    definition TEXT NOT NULL,
    source TEXT DEFAULT 'ozhegov',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Создаем индекс для быстрого поиска по слову
CREATE INDEX IF NOT EXISTS idx_definitions_word ON definitions (word);

-- Добавляем политику (RLS), чтобы любой мог читать, но не писать
ALTER TABLE definitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public definitions access" ON definitions
    FOR SELECT
    USING (true);
